#!/bin/sh

bun build.js
cd docs
cp -fr ../public/* ./
if [ "$(uname)" = "Darwin" ]; then
  echo "Running on macOS"
  gsed -i 's/..\/..\/..\/public//g' main.js
  gsed -i 's/\/images/.\/images/g' main.js
else
  sed -i 's/..\/..\/..\/public//g' main.js
  sed -i 's/\/images/.\/images/g' main.js
fi

